Repository jhnc-oss/meta-python2-backport, pull requests merged in 2022-05, with the labels that each got.

#17 Fail CI build on reported linter issues
  .oelint.cfg
Labels: ci

#18 Fixes for python2 compatibility
  recipes-devtools/python-pytest-json-report/python-pytest-json-report/python2.patch
  recipes-devtools/python-pytest-json-report/python-pytest-json-report_1.5.0.bb
  recipes-devtools/python-pytest-metadata/python-pytest-metadata/python2.patch
  recipes-devtools/python-pytest-metadata/python-pytest-metadata_1.11.0.bb
  recipes-devtools/python-pytest-timeout/python-pytest-timeout/python2.patch
  recipes-devtools/python-pytest-timeout/python-pytest-timeout_1.4.2.bb
Labels: recipe: update

#19 Add missing dependency of pytest-metadata
  recipes-devtools/python-pytest-metadata/python-pytest-metadata_1.11.0.bb
Labels: recipe: update

#20 Fix typo
  recipes-devtools/python-pytest-metadata/python-pytest-metadata_1.11.0.bb
Labels: bug

#23 Increase layer prio to 8
  conf/layer.conf
Labels: enhancement

#25 Remove unused 'PYPI_SOURCE_URI'
  recipes-devtools/python-pytest-json-report/python-pytest-json-report_1.5.0.bb
  recipes-devtools/python-pytest-metadata/python-pytest-metadata_1.11.0.bb
  recipes-devtools/python-pytest-timeout/python-pytest-timeout_1.4.2.bb
Labels: enhancement
